highfidelity/hifi_tests

scripts/benchLocalhost.js
=> Adding another benchmark

benchmarks/dev-welcome_clean-cache.js, benchmarks/tutorial_clean-cache.js
adding the clean-cache version
=> more benchmarks

benchmarks/benchmarkDevAvatarIsland.js
Creates a trace file 12 seconds long, 2 seconds in each of 6 positions.
=> Added benchmark for dev-avatarIsland

tests/utils/autoTester.js
This needs to be merged to allow me to continue debugging.
=> Cleaner recursive code.

tests/utils/autoTester.js
=> Corrected wrong variable name.

tests/performance/test.js, tests/performance/test.md, tests/performance/testAuto.js
This test works with PR #13154, as it requires a scripting change (to the Test namespace).
=> First performance test.

tests/content/entity/light/point/testRecursive.js, tests/content/entity/light/spot/testRecursive.js, tests/content/entity/light/testRecursive.js, tests/content/entity/material/apply/entities/testRecursive.js, tests/content/entity/material/apply/overlays/testRecursive.js, tests/content/entity/material/apply/testRecursive.js, tests/content/entity/material/testRecursive.js, tests/content/entity/model/testRecursive.js, tests/content/entity/shape/testRecursive.js, tests/content/entity/testRecursive.js, tests/content/entity/zone/testRecursive.js, tests/content/testRecursive.js, tests/engine/controller/testRecursive.js, tests/engine/interaction/pointer/laser/testRecursive.js, tests/engine/interaction/pointer/testRecursive.js, tests/engine/interaction/testRecursive.js, tests/engine/render/effect/haze/testRecursive.js, tests/engine/render/effect/highlight/testRecursive.js, tests/engine/render/effect/testRecursive.js, tests/engine/render/geometry/testRecursive.js, tests/engine/render/lighting/ponctual/testRecursive.js, tests/engine/render/lighting/testRecursive.js, tests/engine/render/material/testRecursive.js, tests/engine/render/shadows/testRecursive.js, tests/engine/render/testRecursive.js, tests/engine/testRecursive.js, tests/testRecursive.js
The procedural test wasn't included as part of the recursive test scripts.
=> Added missing procedural test to recursive scripts.

tests/content/entity/zone/zoneOrientation/test.js
This is a copy-paste error from debugging.
=> Accessing wrong repo.

tests/content/entity/light/point/testRecursive.js, tests/content/entity/light/spot/testRecursive.js, tests/content/entity/light/testRecursive.js, tests/content/entity/material/apply/entities/testRecursive.js, tests/content/entity/material/apply/overlays/testRecursive.js, tests/content/entity/material/apply/testRecursive.js, tests/content/entity/material/testRecursive.js, tests/content/entity/model/testRecursive.js, tests/content/entity/shape/testRecursive.js, tests/content/entity/testRecursive.js, tests/content/entity/zone/testRecursive.js, tests/content/testRecursive.js, tests/engine/controller/testRecursive.js, tests/engine/interaction/pointer/laser/testRecursive.js, tests/engine/interaction/pointer/testRecursive.js, tests/engine/interaction/testRecursive.js, tests/engine/render/effect/haze/testRecursive.js, tests/engine/render/effect/highlight/testRecursive.js, tests/engine/render/effect/testRecursive.js, tests/engine/render/geometry/testRecursive.js, tests/engine/render/lighting/ponctual/testRecursive.js, tests/engine/render/lighting/testRecursive.js, tests/engine/render/material/testRecursive.js, tests/engine/render/shadows/testRecursive.js, tests/engine/render/testRecursive.js, tests/engine/render/textures/testRecursive.js, tests/engine/testRecursive.js, tests/testRecursive.js
The automatically generated  recursive scripts had a misplaced semicolon.
=> Fixed misplaced semicolon in recursive test scripts.

tests/engine/controller/keyEvent/keyPressEvent.js, tests/engine/controller/keyEvent/testStory.md
Use notifications to display keys pressed.
=> Updated MD file to require Verbose Logging

tests/content/entity/light/point/testRecursive.js, tests/content/entity/light/spot/testRecursive.js, tests/content/entity/light/testRecursive.js, tests/content/entity/material/apply/entities/testRecursive.js, tests/content/entity/material/apply/overlays/testRecursive.js, tests/content/entity/material/apply/testRecursive.js, tests/content/entity/material/testRecursive.js, tests/content/entity/model/testRecursive.js, tests/content/entity/shape/testRecursive.js, tests/content/entity/testRecursive.js, tests/content/entity/zone/testRecursive.js, tests/content/testRecursive.js, tests/engine/controller/testRecursive.js, tests/engine/interaction/pointer/laser/testRecursive.js, tests/engine/interaction/pointer/testRecursive.js, tests/engine/interaction/testRecursive.js, tests/engine/render/effect/haze/testRecursive.js, tests/engine/render/effect/highlight/testRecursive.js, tests/engine/render/effect/testRecursive.js, tests/engine/render/geometry/testRecursive.js, tests/engine/render/lighting/ponctual/testRecursive.js, tests/engine/render/lighting/testRecursive.js, tests/engine/render/material/testRecursive.js, tests/engine/render/shadows/testRecursive.js, tests/engine/render/testRecursive.js, tests/engine/render/textures/testRecursive.js, tests/engine/testRecursive.js, tests/testRecursive.js
=> Simplified the recursive scripts.

tests/engine/render/effect/haze/color/test.js, tests/engine/render/effect/haze/glare_large/test.js, tests/engine/render/effect/haze/glare_small/test.js, tests/engine/render/effect/haze/high_range/test.js, tests/engine/render/effect/haze/low_range/test.js, tests/engine/render/effect/haze/low_range_high_base_low_ceiling/test.js, tests/engine/render/effect/haze/low_range_high_ceiling/test.js, tests/engine/render/effect/haze/low_range_low_ceiling/test.js, tests/engine/render/effect/haze/none/test.js, tests/engine/render/effect/haze/partial_sky/test.js, tests/engine/render/effect/haze/setup.js, tests/engine/render/effect/haze/visible_sky/test.js, tests/engine/render/shadows/front/test.js, tests/engine/render/shadows/grazing/test.js, tests/engine/render/shadows/normal/test.js, tests/engine/render/shadows/setup.js, tests/utils/autoTester.js
=> Get origin frame

tests/engine/interaction/pointer/laser/laserPointerUtils.js
To return objects to their original position.
=> Shifted laser objects up 1 metre.

tests/engine/interaction/pointer/laser/centerEndY/test.js, tests/engine/interaction/pointer/laser/distanceScaleEnd/test.js, tests/engine/interaction/pointer/laser/enable/test.js, tests/engine/interaction/pointer/laser/faceAvatar/test.js, tests/engine/interaction/pointer/laser/ignore/test.js, tests/engine/interaction/pointer/laser/laserPointerUtils.js, tests/engine/interaction/pointer/laser/lockEnd/test.js, tests/engine/interaction/pointer/laser/lockEndUUID/test.js, tests/engine/interaction/pointer/laser/renderState/test.js
Variables were being initialized in an include file used by multiple tests.  JavaScript does not re-include the file each time...
=> DO NOT INITIALIZE DATA IN AN INCLUDE FILE

tests/content/entity/material/apply/avatars/test.js, tests/engine/interaction/pointer/laser/ignore/test.js, tests/utils/autoTester.js
1.  Does not use "mirror" mode for the avatar material mode.  This is to overcome an inconsistency in the Camera.setModeString command.
2.  Sets the view to independent before setting its pose.
3.  Improved the laser/ignore test.
=> Test updates

tests/content/entity/light/point/create/test.js
1st test of new "branch" mechanism.
=> First test.

tests/engine/interaction/pointer/laser/ignore/test.js
For some stupid reason - the view angles are wrong.
=> Set all angles to 0.

batch files/DailyTests.bat
In addition - warn if missing branch parameter.
=> Delete PNGs before starting new test.

tests/engine/render/effect/haze/color/test.js, tests/engine/render/effect/haze/glare_large/test.js, tests/engine/render/effect/haze/glare_small/test.js, tests/engine/render/effect/haze/high_range/test.js, tests/engine/render/effect/haze/low_range/test.js, tests/engine/render/effect/haze/low_range_high_base_low_ceiling/test.js, tests/engine/render/effect/haze/low_range_high_ceiling/test.js, tests/engine/render/effect/haze/low_range_low_ceiling/test.js, tests/engine/render/effect/haze/none/test.js, tests/engine/render/effect/haze/partial_sky/test.js, tests/engine/render/effect/haze/setup.js, tests/engine/render/effect/haze/visible_sky/test.js, tests/engine/render/shadows/front/test.js, tests/engine/render/shadows/grazing/test.js, tests/engine/render/shadows/normal/test.js, tests/engine/render/shadows/setup.js, tests/utils/autoTester.js
`getOriginFrame` has been added to autoTester.js
The shadow and haze tests have been updated to use this method.
=> Implementation of getOriginFrame

tests/testRecursive.js
Reverts highfidelity/hifi_tests#195
=> Revert "Testing"

tests/testRecursive.js
Reverts highfidelity/hifi_tests#194
=> Revert "Testing."

tests/testRecursive.js
Reverts highfidelity/hifi_tests#192
=> Revert "Testing new recursive script."

tests/utils/autoTester.js, tests/utils/branchUtils.js
Added methods to return the user and the repository.  This will allow running tests from any GitHub repo, as well as simplify some of the tests (specifically - use of assets).
=> Improved API

tests/engine/render/geometry/skinning/create.js
This test was not updated with the the new test_stage.js` API (test is not an automated test).
=> Fixed broken skinning test

tests/content/entity/model/physics/testStory.js
The missing definition of `autoTester` has been added.
=> First fix to physics.

tests/engine/interaction/pointer/laser/collision/collision.js, tests/engine/interaction/pointer/laser/joint/joint.js, tests/engine/interaction/pointer/laser/mouse/mouse.js, tests/engine/interaction/pointer/laser/scaleWithAvatar/scaleWithAvatar.js, tests/utils/autoTester.js
These tests are only run manually.  They have been updated to use the new `laserUtils.js` API.
=> Fix user story tests

tests/content/entity/model/physics/testStory.md
Updates Draw Collision Shapes to Bullet Collision option in test story. I do not have permission to upload a new picture for the expected results. I will attach that in a comment below.
=> Update Collision test to use new Bullet Collision.

tests/content/entity/light/point/create/test.js, tests/utils/autoTester.js
The secondary camera is turned off after the completion of the test - if the test has turned the camera on.
Turning the camera just for the snapshot does not work (as no image will be rendered).
=> Sec cam on as needed

benchmarks/Spot500/bot-for-spot.js, benchmarks/Spot500/spot-manual.js
Adding the script used for the bot (as an agent of the server)
Adding a specialized version of manual.js to spawn My avatar at the correct space
=> Spot500: adding new benchmark folder as we work on getting 500 avatars in the SPot

tests/engine/render/effect/bloom/test.js
https://github.com/highfidelity/hifi/pull/13778
=> Update bloom test

tests/content/entity/particleEffect/alpha/test.md, tests/content/entity/particleEffect/color/test.md, tests/content/entity/particleEffect/emitterShouldTrail/test.md, tests/content/entity/particleEffect/isEmitting/test.md, tests/content/entity/particleEffect/radius/test.md, tests/content/entity/particleEffect/spin/test.md
(Automatically) created MD files for the particle tests.
=> Added MD files.

tests/content/entity/light/point/create/test.js, tests/content/entity/light/spot/create/test.js
The dimensions of the lights were mistakenly removed.
1. Run https://raw.githubusercontent.com/highfidelity/hifi_tests/master/tests/content/entity/light/testRecursive.js
2.  Verify the 2 created snapshots are correct.
=> Fix light tests that I broke

tests/utils/deleteNearbyEntities.js
Stop the script after completion.  This is needed to shutdown Interface after entities have been removed.
=> Add stop to script

tests/content/entity/model/modelReaders/fbxReader/simple/test.js, tests/content/entity/model/modelReaders/fbxReader/still_life/test.js, tests/content/entity/model/modelReaders/objReader/still_life/test.js, tests/content/entity/parenting/test.js, tests/content/entity/zone/shadowControl/test.js, tests/engine/controller/reticle/test.js, tests/engine/render/camera/primary/test.js, tests/engine/render/camera/secondary/test.js, tests/engine/render/mesh/MyAvatar/scale/test.js, tests/engine/render/mesh/MyAvatar/visibility/test.js, tests/performance/graphics/triangles/testStory.js
https://highfidelity.fogbugz.com/f/cases/20969/Improve-zone-definition-for-some-tests
Adds missing fields to the zone used in a number of tests.
1.  Run nitpick
2.  Set Github user to `NissimHadar` and branch to `20969-improveZoneDefinition`
3.  Run the full test suite and verify no new failures (especially the images with the yellow background)
=> Case 20969 - Added missing properties, so as not to use defaults.

tests/engine/render/effect/bloom/test.js, tests/engine/render/effect/haze/setup.js, tests/engine/render/shadows/setup.js
https://highfidelity.fogbugz.com/f/cases/21310/Correct-scaling-of-sphere-model-in-tests
=> Case 21310: correct scaling of sphere model

tests/engine/interaction/pointer/laser/distanceScaleEnd/test.js, tests/engine/interaction/pointer/laser/distanceScaleEnd/test.md, tests/engine/interaction/pointer/laser/enable/test.js, tests/engine/interaction/pointer/laser/enable/test.md, tests/engine/interaction/pointer/parabola/enable/test.js, tests/engine/interaction/pointer/parabola/enable/test.md
https://highfidelity.fogbugz.com/f/cases/21620/Fix-laser-tests
=> Case 21620: separated snapshot taking into separate steps.

tests/utils/nitpick.js
https://highfidelity.fogbugz.com/f/cases/21941/
=> Case 21941: Always set LOD, and restore on test completion.

tests/content/entity/material/apply/avatars/test.js, tests/content/entity/zone/zoneEffects/test.js, tests/engine/render/effect/highlight/coverage/test.js
content / entity / material / apply / avatars
engine / render / effect / highlight / coverage
content / entity / zone / zoneEffects
=> Add delays to some finicky tests
